title: Near Realâ€“Time Freeway Accident Detection Using Speed Data
description: Yasitha Liyanage, Rahul Kar
theme: jekyll-theme-cayman
show_downloads: False
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
